### ISSUE TITLE
Serialization xml crash in demo 

### ISSUE THREAD

**Issue by dingxiaolong** [rolfbjarne/xamarin-macios#4] opened 2023-03-21 08:25 UTC
Hi, I download the demo "MySimpleApp" in your source code ,but always face this error:

![image](https://user-images.githubusercontent.com/21192107/226550055-06827576-9f24-4a1a-8c62-9251be4f03cf.png)

Can u help check whether it run successfully now ?
Many thanks. Br.

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Serialization xml successfully .

### Actual Behavior
Crash when instance .

### Environment
My visual studio version is  17.5.2 (build 14).
Mac os version is 12.6.3.

```
```

### Example Project (If Possible)
https://github.com/xamarin/xamarin-macios/tree/6.0.x/tests/dotnet/MySimpleApp

**Comment by rolfbjarne** [comment] 2023-03-21 09:43
The AppDelegate file that shows up in your screenshot from the IDE looks nothing like the AppDelegate.cs file in the MySimpleApp project:

https://github.com/xamarin/xamarin-macios/blob/6.0.x/tests/dotnet/MySimpleApp/AppDelegate.cs

**Comment by dingxiaolong** [comment] 2023-03-22 01:40
Thanks for your quick feedback.  Sorry for the misunderstanding .

I download the code directly yesterday ,but can't find the branch now ....
The branch should be "xamarin-macios-c8014a6b6fd759159b409df19062f11b57ae8e2c". Seems it have been deleated or someting..
![image](https://user-images.githubusercontent.com/21192107/226778958-f512f079-2665-4d22-b56e-dfbaaf27ea63.png)


I upload this MySimpleApp project to here :https://github.com/dingxiaolong/TestIOSXml

Could you help check it please .
Many thanks. Br.

**Comment by dingxiaolong** [comment] 2023-03-22 03:28
I have found the project , the url is https://github.com/rolfbjarne/xamarin-macios/tree/c8014a6b6fd759159b409df19062f11b57ae8e2c/tests/dotnet/MySimpleApp.

**Comment by rolfbjarne** [comment] 2023-03-22 07:08
This looks like a duplicate of https://github.com/dotnet/maui/issues/14086, so I'm closing this.

**Closed as not planned by rolfbjarne** 2023-03-22 07:08 UTC
